### ISSUE TITLE
Glitching on Stock Android

### ISSUE THREAD

**Issue by aholla** [pixijs/pixi-spine#4] opened 2015-03-31 09:16 UTC
If you run a spine animation in the stock android browser (Samsung Phones/tablets) you will see the animation "glitches". It is random and affects animations differently but you can expect to see it's positions jump or the rotation jump and then back to normal.

I have tested the example from esoteric and it works fine so must be something in pixi. Also there is a createJS version that is based upon the pixi version that also works fine.

http://esotericsoftware.com/files/runtimes/spine-js/example/
http://www.patrickmatte.com/?p=450

ALso I have noticed in the demo "spineboy" when running in PIXI, the characters "right thigh" (near side) is not anchored correctly. It looks like it is anchored in the center but should be anchored at the top/character hip.

**Comment by adamdanielsdesign** [comment] 2015-03-31 15:41
If this is the same deal (issue with draw order), try using the pixi.js from the 2.x branch, it should have fixes in place already.

**Comment by aholla** [comment] 2015-03-31 15:45
Ah sorry, I should have said which version I'm using. I initially found the bug with version 2 but I have just tested it with the current dev branch (version 3 rc4) and the problem still exists. I am not sure what the differences are between the 2.x branch and the dev branch.

**Comment by adamdanielsdesign** [comment] 2015-03-31 15:46
Try the 2.x branch anyways just in case.

**Comment by adamdanielsdesign** [comment] 2015-03-31 15:53
Pretty sure the difference is that any versions with rc#(release candidate)  as a prefix haven't been released yet.

**Comment by aholla** [comment] 2015-03-31 16:35
Hi so I tried out the build from the the 2.x branch and the problems still exist.

I have created a little video that hopefully demonstrates the bug. The video starts once the Spine animation has loaded and had been added to the stage.

It does not have an animation state yet so is standing still but you can see the position if the animation changes every now and then. (If the animations are rotated similar rotation glitches happen.) I then enable the running animation and although it is harder to see, the animation still "glitches". Also if you look at the running animation you can see the front thigh is not anchored correctly.

https://www.youtube.com/watch?v=9E-wcmCdXqk&edit=vd

This happens only in the stock android browser.

**Comment by adamdanielsdesign** [comment] 2015-03-31 16:53
Not related then to the drawOrder deal. I just started working with v3, looks like Spine may need to be updated with any changes from v2, worldPosition/etc.

**Comment by englercj** [comment] 2015-03-31 17:22
@adamdanielsdesign I will be migrating the v3 branch to use the new spine repo at pixijs/pixi-spine which has the fixes made in the v2 spine implementation merged in.

**Comment by adamdanielsdesign** [comment] 2015-03-31 17:25
Tx! Also, I just made a wiki page for basic usage of the plugin with v3. It would work as a fast start and detail on proper usage. So far I'm getting errors on errors. The loader was changed, then passing the correct values and using the correct classes for instantiation gives back errors.

**Comment by adamdanielsdesign** [comment] 2015-03-31 17:30
For the android glitch, pretty sure the issue is an NaN value somewhere. I saw that the renderer changed to not need a stage object; if the world position is now based of window size/etc vs a static value that may be the debug on why the android browser isn't working if it's browser doesn't init with that event data.

**Comment by englercj** [comment] 2015-04-01 15:00
The v3 branch now uses this repo, specifically v1.0.1.

**Comment by adamdanielsdesign** [comment] 2015-04-01 17:35
@englercj I opened an issue on Esoteric's github account for the FPS issue: https://github.com/pixijs/pixi-spine/issues/1.  I'm considering rebuilding the Spine plugin as an option. It seems to me that the dev version isn't literate enough and needs better organization to it's data model.

**Comment by ivanpopelyshev** [comment] 2015-04-07 15:41
Its glitching in iOS too, but different. I'll try to test and fix it on tablets.

**Comment by cursedcoder** [comment] 2017-02-10 05:24
very old issue, my skeletons don't have any issues on ios/android, so closing, please open another issue if you encounter glitching in 2017

**Closed by cursedcoder** 2017-02-10 05:24 UTC
